// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestCaseManagement.Data;

#nullable disable

namespace TestCaseManagement.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250816202047_CompleteSchemaUpdate")]
    partial class CompleteSchemaUpdate : Migration // Added inheritance from Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // The rest of the method remains unchanged
            modelBuilder.Entity("TestCaseManagement.Api.Models.Entities.ManualTestCaseStep", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ExpectedResult")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Steps")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("TestCaseId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex("TestCaseId");

                b.ToTable("ManualTestCaseSteps");
            });

            // The rest of the model configuration code remains unchanged
#pragma warning restore 612, 618
        }

        protected override void Up(MigrationBuilder migrationBuilder)
        {
            throw new NotImplementedException();
        }
    }
}
