// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestCaseManagement.Data;

#nullable disable

namespace TestCaseManagement.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250817084835_UpdateTestSuiteTestCaseService")]
    partial class UpdateTestSuiteTestCaseService
    {
    }
}
